### ISSUE TITLE
Czech VAT IDs may be longer than 8 digits

### ISSUE THREAD

**Issue by jakejanson** [DragonBe/vies#30] opened 2017-08-17 15:51 UTC
Hello. According to the source code of the class `DragonBe\Vies\Validator\ValidatorCZ`, a Czech VAT ID must be 8 digits long, but thatʼs wrong. Our law states that a VAT ID consists of the prefix “CZ” and one of the following:

* for individiuals: their personal identification number, or other general identificator if specified by a special law
* for companies and other legal entities: their taxpayer identification number
* in case the entity doesnʼt have a general identificator assigned, the tax administrator can assign a custom identificator

Example: `CZ699004237` is a valid VAT ID, but this library marks it as invalid.

Iʼm afraid that there is no way of strictly checking the formal validity of the VAT ID before submitting it to VIES. I personally have seen only VAT IDs that are (excluding the “CZ“ prefix) 8, 9 or 10 digits long, but I could not find any legal evidence that indicate these are the only valid formats.

**Comment by krzaczek** [comment] 2017-08-17 16:13
Hi,

That is true: 
'CZ'+8-10 digits
Source: https://en.m.wikipedia.org/wiki/VAT_identification_number

I need to find a checksum algo for 9 and 10 digits to be able to implement it.

pawel (at) mobile

**Comment by krzaczek** [comment] 2017-08-17 16:18
Found it: http://85.81.229.78/systems/DKVIES/-%20Arkiv/Algoritme%E6ndringer/VIES-VAT%20Validation%20Routines-v15.0.doc

pawel (at) mobile

**Comment by DragonBe** [comment] 2017-08-17 17:05
On the EU VIES FAQ pages I found a [link](http://www.financnisprava.cz/cs/mezinarodni-spoluprace/mezinarodni-spoluprace-a-dph/dph-v-eu/overovani-dic-vat-id) to more information, unfortunately Google makes a bit of a mess out of it. But maybe it will make more sense to all of you.

The document you provided offers the same as what's being implemented: 8-10 numeric values. Can you offer me a unit test (or other form of test) to see where it fails? I can't seem to reproduce it.

**Comment by krzaczek** [comment] 2017-08-17 17:17
At this moment the library only supports 8 digit numbers (https://github.com/DragonBe/vies/blob/master/src/Vies/Validator/ValidatorCZ.php#L44)

I will implement 9 and 10 digit numbers .. maybe tomorrow or next week.

**Comment by krzaczek** [comment] 2017-08-17 17:24
For example CZ7103192745 - this is a valid VAT number and it's successfully validated by VIES - but the library will return false since it's longer than 8 digits

**Comment by krzaczek** [comment] 2017-08-18 12:43
@DragonBe I have created a patch for version 1.0.x. Can You create a 1.0 branch from tag 1.0.6 - I'll send a pull request. I'll try to create a PHP 7.1 patch during the weekend. 

https://github.com/krzaczek/vies/tree/1.0

**Comment by DragonBe** [comment] 2017-08-18 14:45
crap, should have used the command line… merged into master 🤦‍♂️ 

Reverting changes and merging it into 1.0 branch… hang on

**Closed** 2017-08-18 14:53 UTC

**Comment by DragonBe** [comment] 2017-08-18 15:11
Fixed my sleepy PR acceptance, all is good to go.

![screen shot 2017-08-18 at 17 09 27](https://user-images.githubusercontent.com/282825/29465048-25b39d02-8438-11e7-967f-be7671d31fa5.png)

Will tag it as 1.0.7 and forward your changes on 2.0 branch

**Comment by DragonBe** [comment] 2017-08-18 15:27
Ok, tagged 1.0.7 and 2.0.1 with updated CZ validation rules. Thank you @jakejanson for reporting the issue and @krzaczek to come up quickly with an update. You both are heroes in my book, thanks a bunch! 🙇

**Comment by jakejanson** [comment] 2017-08-18 23:06
@krzaczek wow, that was fast. Thank you!
@DragonBe this was my first OSS bug report, I hope I did well 😅 Anyway, thanks for this amazing library!

**Comment by DragonBe** [comment] 2017-08-19 15:02
@jakejanson you're welcome, glad you like this library.
